### ISSUE TITLE
datasets access problem.

### ISSUE THREAD

**Issue by HXYNODE** [DustinAlandzes/machine-learning-with-python-cookbook-notes#2]
Why couldn't I get titanic data file from the tiny url provided by author? I couldn't access it. How did you get it？Could you help me? Thanks~

**Comment by DustinAlandzes** [comment]
Looks like it directs to: https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/titanic.csv

if you still have this problem try
```
url = "https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/titanic.csv"
```

**Comment by HXYNODE** [comment]
get√ thank you very much!
